version: '3'

services:

  landing:
    container_name: landing
    build:
      context: ./landing
      dockerfile: Dockerfile
    networks:
      - test-network
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: lucastercas.dns-cloud.net
      LETSENCRYPT_HOST: lucastercas.dns-cloud.net
      LETSENCRYPT_EMAIL: lucasmtercas@gmail.com

  proxy:
    image: jwilder/nginx-proxy
    container_name: sairmais_proxy
    networks:
      - test-network
    depends_on:
      - api
      - partner
      - customer
      - landing
      - admin
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  certs:
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - test-network
    container_name: sairmais_certs
    depends_on:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    environment:
      DEFAULT_EMAIL: lucasmtercas@gmail.com
      NGINX_PROXY_CONTAINER: sairmais_proxy

networks:
  test-network:
    driver: bridge

volumes:
  nginx-certs:
  nginx-vhosts:
  nginx-html:
